# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Hours', models.IntegerField(default=3)),
                ('Grouping', models.CharField(max_length=50)),
                ('Conexion', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Notes', models.CharField(max_length=50)),
                ('NotesDept', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=30)),
                ('building', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chours', models.IntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='Group',
            field=models.ManyToManyField(to='timetabledata.Group'),
        ),
        migrations.AddField(
            model_name='data',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Room'),
        ),
        migrations.AddField(
            model_name='data',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Teacher'),
        ),
    ]
