# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0002_auto_20180622_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('Teacher', 'Conexion'), ('Room', 'Conexion'), ('Grouping', 'Conexion')]),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('name', 'course')]),
        ),
    ]
