# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0003_auto_20180623_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Students',
            field=models.IntegerField(blank=True, default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='Conexion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Group',
            field=models.ManyToManyField(blank=True, to='timetabledata.Group'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Grouping',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Language',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='Notes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='NotesDept',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='Room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Room'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
