# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0004_auto_20180623_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Room'),
        ),
    ]
