# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0007_auto_20180623_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Grouping',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
