# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0008_auto_20180623_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_Id', models.IntegerField()),
                ('Group_Id', models.IntegerField()),
                ('Subject', models.CharField(max_length=50)),
                ('Duration', models.IntegerField()),
                ('Students', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConexionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(blank=True, choices=[('ME', 'Meeting'), ('OP', 'Option'), ('NO', 'Nothing'), ('IN', 'Indepednent')], max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='Type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timetabledata.ConexionType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Data'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='timetabledata.Tag'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Teachers',
            field=models.ManyToManyField(blank=True, to='timetabledata.Teacher'),
        ),
    ]
