# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0013_auto_20180624_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='chours',
            new_name='contractHours',
        ),
        migrations.AddField(
            model_name='teacher',
            name='FreeType',
            field=models.CharField(choices=[('FH', 'FirstHours'), ('DF', 'DayFree'), ('NO', 'Nothing')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='MaxBuildingChangesWeek',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='MaxGapsDay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='MaxGapsWeek',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='MaxSpanDay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classHours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='compensationHours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='complementaryHours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='guardHours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='maxDaysWeek',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tutCompHours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tutHours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Data'),
        ),
    ]
