# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0020_auto_20180625_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Data'),
        ),
        migrations.AlterField(
            model_name='conexiontype',
            name='ctype',
            field=models.CharField(blank=True, choices=[('ME', 'Meeting'), ('OP', 'Option'), ('NO', 'Nothing'), ('IN', 'Indepednent')], max_length=2, unique=True),
        ),
    ]
