# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0021_auto_20180626_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityConexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conexion', models.CharField(max_length=50)),
                ('subconexion', models.CharField(max_length=52)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Data'),
        ),
        migrations.AddField(
            model_name='activityconexion',
            name='activity',
            field=models.ManyToManyField(blank=True, to='timetabledata.Activity'),
        ),
    ]
