# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0022_auto_20180626_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group', models.ManyToManyField(to='timetabledata.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Data'),
        ),
    ]
