# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabledata', '0023_auto_20180627_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupings',
            name='course',
            field=models.CharField(default='course', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabledata.Data'),
        ),
    ]
